apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rumbling
  name: rumbling
  namespace: argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rumbling
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rumbling
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
~                       
